# Generated by Django 5.1.1 on 2024-10-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_merge_20241017_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_ingreso', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='estado_ingreso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='lugar_ingreso',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
