# Generated by Django 5.1.1 on 2024-10-25 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_estadoingreso_participante_estado_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='estado_ingreso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.estadoingreso'),
        ),
    ]
