# Generated by Django 5.1.1 on 2024-10-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_alter_participante_estado_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='lugar_ingreso',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
