# Generated by Django 5.1.1 on 2024-10-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_alter_participante_lugar_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albergue',
            old_name='fecha_ingreso',
            new_name='fecha_ingreso_albergue',
        ),
    ]
